# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gpxi_int <- function(i, m, beta, S0, S1, sig2) {
    .Call(`_SurrogateBMA_gpxi_int`, i, m, beta, S0, S1, sig2)
}

rcpp_hello_world <- function() {
    .Call(`_SurrogateBMA_rcpp_hello_world`)
}

